#!/usr/bin/env ansible-playbook
---
- hosts: all_vms
  gather_facts: false
  serial: "{{ serial|default(omit) }}"
  strategy: free

  roles:
    - role: os_specific_vars

    - role: vmware_vmrun
      action: create_vm

    - role: rhsm_register

    - role: basic_packages

- hosts: test_vms
  roles:
    - role: startup_script
  strategy: free

- hosts: dev_vms
  roles:
    - role: dev_setup
  strategy: free

