#!/usr/bin/env ansible-playbook
---
- hosts: all_vms
  gather_facts: false

  pre_tasks:
    - include_vars: local_vars.yml

  roles:
    - role: os_specific_vars

    - role: vmware_vmrun
      action: create_vm

    - role: rhsm_register

    - role: packages

    - role: startup_script

- hosts: dev_vms
  roles:
    - role: dev_setup
