#!/usr/bin/env ansible-playbook
---
- hosts: all_vms
  gather_facts: false
  serial: "{{ serial|default(omit) }}"
  strategy: free

  roles:
    - role: os_specific_vars

    - role: vmware_vmrun
      action: create_vm

    - role: rhsm_register

    - role: basic_packages

    - role: startup_script
      when: "'test_vms' in group_names"

    - role: dev_setup
      when: "'dev_vms' in group_names"

    - role: vmware_vmrun
      action: snapshot_vm
      ignore_errors: yes
      when: "bssd|default(False)"

    - role: vmware_vmrun
      action: shutdown_vm
      when: "bssd|default(False)"

