#!/usr/bin/env ansible-playbook
---
- hosts: all_vms
  gather_facts: false
  pre_tasks:
    - include_vars: local_vars.yml
  roles:
    - role: vmware_vmrun
      action: unsnapshot_vm
      ignore_errors: yes

