---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'           # CentOS-6.5
        - '{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml'              # RedHat-6.5
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'     # CentOS-6
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-6
        - '{{ ansible_distribution }}.yml'                                              # CentOS
        - '{{ ansible_os_family }}.yml'                                                 # RedHat
        - 'default.yml'
      paths: '../vars'

- block:

    - name: Update apt cache
      apt:
        update_cache: True

  rescue:

    - name: Clear stale cache
      file:
        path: /var/lib/apt/lists
        state: absent

    - name: Update apt cache via command
      command: "apt-get update"

- name: Install packages via yum
  yum:
    name: '{{ item }}'
    state: installed
  with_items: "{{ yum_packages }}"

- name: Install additional apt repositories
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repos }}"

- name: Install packages via apt-get
  apt:
    name: '{{ item }}'
    state: installed
  with_items: "{{ apt_packages }}"

