---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'           # CentOS-6.5
        - '{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml'              # RedHat-6.5
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'     # CentOS-6
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-6
        - '{{ ansible_distribution }}.yml'                                              # CentOS
        - '{{ ansible_os_family }}.yml'                                                 # RedHat
        - 'default.yml'
      paths: '../vars'

# RPM-based package installation

- name: Install additional yum repositories
  yum_repository:
    name: '{{ item.name }}'
    baseurl: '{{ item.baseurl|default(omit) }}'
    mirrorlist: '{{ item.mirrorlist|default(omit) }}'
  with_items: '{{ repos }}'
  when: ansible_os_family == 'RedHat'

- name: Install packages via yum
  yum:
    name: '{{ item }}'
    state: installed
  with_items: "{{ packages }}"
  when: ansible_os_family == 'RedHat'

# Apt-based package installation

- block:
    - name: Update apt cache
      apt:
        update_cache: True
  rescue:
    - name: Clear stale cache
      file:
        path: /var/lib/apt/lists
        state: absent
    - name: Update apt cache via command
      command: "apt-get update"
  when: ansible_os_family == 'Debian'

- name: Install additional apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
  with_items: "{{ repos }}"
  when: ansible_os_family == 'Debian'

- name: Install packages via apt-get
  apt:
    name: '{{ item }}'
    state: installed
  with_items: "{{ packages }}"
  when: ansible_os_family == 'Debian'

