- name: Create tmp directory
  file:
    path: "{{ vm_path }}"
    state: directory
  delegate_to: localhost

- name: Copy scripts to tmp folder
  template:
    src: "{{ item }}"
    dest: "{{ vm_path }}/{{ item }}"
  with_items:
    - autounattend.xml
    - SetIPAddress.bat
    - ConfigureRemotingForAnsible.ps1
  register: tmp_scripts
  delegate_to: localhost

- name: Copy extra packages to tmp folder
  copy:
    src: "{{ downloads_path }}/extra_windows/{{ item }}"
    dest: "{{ vm_path }}/{{ item }}"
  with_items:
    - vmware-tools-setup64.exe
  register: tmp_extras
  delegate_to: localhost

- name: Create autounattend ISO
  command: "\"{{ vmware_library_path }}/mkisofs\" -o \"{{ kickstart_iso_filename }}\" -R -J -V -T {{ tmp_scripts.results|map(attribute='item')|join(' ') }} {{ tmp_extras.results|map(attribute='item')|join(' ') }}"
  args:
    chdir: "{{ vm_path }}"
  delegate_to: localhost

- name: Remove temporary files
  file:
    path: "{{ vm_path }}/{{ item }}"
    state: absent
  with_flattened:
    - "{{ tmp_scripts.results|map(attribute='item')|shuffle }}"
    - "{{ tmp_extras.results|map(attribute='item')|shuffle }}"
  delegate_to: localhost

