---
- name: Snapshot the VM
  command: "\"{{ vmware_library_path }}/vmrun\" -T {{ vmware_platform }} snapshot \"{{ vmx_filename }}\" \"{{ snapshot_name }}\""
  args:
    chdir: "{{ vm_path }}"
  delegate_to: localhost
  register: result
  failed_when: (result.rc != 0) and ('A snapshot with the name already exists' not in result.stdout)
  changed_when: (result.rc == 0)
  serial: 1
