---

# Ubuntu Dev Box Setup

- name: Install graphical desktop
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - "ubuntu-standard"
    - "ubuntu-desktop"
    - "open-vm-tools-desktop"
    - "xserver-xorg-input-mouse"
    - "xserver-xorg-video-vmware"
    - "indicator-session"
    - "unity-lens-applications"
    - "acpi-support"
    - "branding-ubuntu"
    - "firefox"
    - "fonts-liberation"
    - "gnome-accessibility-themes"
    - "gnome-terminal"
    - "mousetweaks"
    - "nautilus-share"
    - "network-manager-gnome"
    - "plymouth-theme-ubuntu-logo"
    - "xdg-utils"
    - "xterm"
  notify:
    - reboot
    
- name: Check locale
  command: "localectl"
  register: localectl_result
  changed_when: False

- name: Set locale
  command: "localectl set-locale LANG=\"en_US.UTF-8\""
  when: '"System Locale: LANG=en_US.UTF-8" not in localectl_result.stdout'
  notify:
    - reboot

- name: Add node.js repo
  template:
    src: 'nodejs_deb.j2'
    dest: '/etc/apt/sources.list.d/nodesource.list'

- name: Install dev tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - "gcc"
    - "make"
    - "git"
    - "nodejs"
    - "python-setuptools"
    - "python-virtualenv"
    - "pbuilder"
    - "debhelper"
    - "reprepro"
    - "docker.io"
    - "apache2"

- name: Start needed services
  service:
    name: "{{ item }}"
    state: running
    enabled: True
  with_items:
    - "docker"
    - "apache2"
