---

# Ubuntu Dev Box Setup

- name: Install dev packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "ubuntu-standard"
    - "ubuntu-desktop"
    - "xserver-xorg-input-all"
    - "open-vm-tools-desktop"
    - "git"

- name: Check locale
  command: "localectl"
  register: localectl_result
  changed_when: False

- name: Set locale
  command: "localectl set-locale LANG=\"en_US.UTF-8\""
  when: '"System Locale: LANG=en_US.UTF-8" not in localectl_result.stdout'
  notify:
    - reboot

