---
- name: reset
  command: "\"{{ role_path }}/bin/serialize.sh\" \"\\\"{{ vmware_library_path }}/vmrun\\\" -T {{ vmware_platform }} reset \\\"{{ vmx_filename }}\\\"\""
  args:
    chdir: "{{ vm_path }}"
  delegate_to: localhost
  changed_when: False
  notify: wait_for_ip

- name: wait_for_ip
  command: "\"{{ vmware_library_path }}/vmrun\" -T {{ vmware_platform }} getGuestIPAddress \"{{ vmx_filename }}\""
  args:
    chdir: "{{ vm_path }}"
  register: vm_ip_output
  until: (vm_ip_output.rc == 0) and (vm_ip_output.stdout == ansible_ssh_host)
  delay: 15
  retries: 120
  delegate_to: localhost
  changed_when: False

