syntax on
filetype indent on
set backspace=indent,eol,start
au FileType python setl sw=4 sts=4 et
au FileType yaml setl sw=2 sts=2 ai et ts=2
au FileType haskell setl sw=4 sts=4 ai et
au FileType html setl noai sw=4 sts=4 et
au FileType c setl sw=4 sts=4 ai et
au FileType perl setl sw=4 sts=4 ai et
au FileType make set noet sw=8 sts=0
au BufRead,BufNewFile *.mk set syntax=python
au BufRead,BufNewFile *.sls set syntax=yaml
highlight DiffAdd    cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
highlight DiffDelete cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
highlight DiffChange cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
highlight DiffText   cterm=bold ctermfg=10 ctermbg=88 gui=none guifg=bg guibg=Red
