---
- block:
    - name: Update apt cache
      apt:
        update_cache: True
  rescue:
    - name: Clear stale cache
      file:
        path: /var/lib/apt/lists
        state: absent
    - name: Update apt cache via command
      command: "apt-get update"

- name: Install additional apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
  with_items: "{{ repos }}"

- name: Install packages via apt-get
  apt:
    name: '{{ item }}'
    state: installed
  with_items: "{{ packages }}"

- name: Update all installed packages
  apt:
    update_cache: yes
    upgrade: safe

