---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'           # CentOS-6.5
        - '{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml'              # RedHat-6.5
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'     # CentOS-6
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-6
        - '{{ ansible_distribution }}.yml'                                              # CentOS
        - '{{ ansible_os_family }}.yml'                                                 # RedHat
        - 'default.yml'
      paths: '../vars'

# Yum-based package installation

- include: redhat.yml
  when: (ansible_os_family == 'RedHat') and (ansible_distribution != 'Fedora')

# DNF-based package installation

- include: fedora.yml
  when: ansible_distribution != 'Fedora'

# Apt-based package installation

- include: debian.yml
  when: ansible_os_family == 'Debian'

# Windows package installation

- include: windows.yml
  when: ansible_os_family == 'Windows'

