---
- name: Install packages from Chocolatey
  win_chocolatey:
    name: "{{ item }}"
    state: present
    upgrade: True
  with_items:
    - "chocolatey"
    - "putty.install"
    - "googlechrome"

- name: Configure Windows Updates to check only
  win_regedit:
    key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update'
    value: "{{ item }}"
    data: 2
    datatype: dword
  with_items:
    - "AUOptions"
    - "CachedAUOptions"

- name: Apply all available Windows updates
  win_updates:
    state: installed

