---
vmware_guest_os: 'centos-64'
vmx_template: "linux.vmx"
iso_filename: 'CentOS-6.9-x86_64-minimal.iso'
unattend_method: "el-ks"
kickstart_ks_filename: "ks6.cfg"
network_dev: "vmxnet3"
boot_params: 'ks=cdrom:/ks.cfg'
ansible_ssh_user: root
extra_rpms:
  - libdnet-1.12-6.el6.x86_64.rpm
  - libicu-4.2.1-14.el6.x86_64.rpm
  - libmspack-0.5-0.1.alpha.el6.x86_64.rpm
  - open-vm-tools-9.10.2-3.el6.x86_64.rpm
  - libselinux-python-2.0.94-7.el6.x86_64.rpm
