---
vmware_guest_os: 'windows8srv-64'
vmx_template: "windows.vmx"
iso_filename: '9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso'
unattend_method: "windows"
unattend_filename: "unattend-2012.xml"
network_dev: "e1000e"
network_device_name: "Ethernet0"
scsi_dev: "lsisas1068"
ansible_ssh_user: Administrator
script_files:
  - SetIPAddress.bat
  - ConfigureRemotingForAnsible.ps1
  - RunOnce.cmd
extra_files:
  - vmware-tools-setup64.exe
  - 7z1602-x64.exe
  - chocolatey.0.9.10.3.nupkg
