---
vmware_guest_os: 'windows9srv-64'
vmx_template: "windows.vmx"
iso_filename: '14300.1000.160324-1723.RS1_RELEASE_SVC_SERVER_OEMRET_X64FRE_EN-US.ISO'
unattend_method: "windows"
unattend_filename: "unattend-2016.xml"
network_dev: "e1000e"
network_device_name: "Ethernet0"
scsi_dev: "lsisas1068"
ansible_ssh_user: Administrator
script_files:
  - SetIPAddress.bat
  - ConfigureRemotingForAnsible.ps1
  - RunOnce.cmd
extra_files:
  - vmware-tools-setup64.exe
  - 7z1602-x64.exe
  - chocolatey.0.9.10.3.nupkg
